# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Release Development

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout wallet
      uses: actions/checkout@v3
      with:
          repository: pandora-cash/PandoraPay-wallet
          path: PandoraPay-wallet
          
    - name: Checkout Blockchain
      uses: actions/checkout@v3
      with:
          repository: pandora-cash/go-pandora-pay
          path: go-pandora-pay          
    
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x        

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19        
        
    - name: Install libraries
      run: sudo apt-get install -y brotli zopfli
                
    - name: Prepare Wasm Build
      run: |   
        go get -t .
      working-directory: ./go-pandora-pay
        
    - name: Install dependencies
      run: |
        npm install
        bash prepare.sh
        bash build.sh        
        cd ./dist
        zip -r build.zip build
      working-directory: ./PandoraPay-wallet
        
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |            
           build.zip
