# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  push:
    tags:
      - "*"

jobs:
  tagged-release:
    name: "Release"

    runs-on: ubuntu-latest
    steps:

    - name: Checkout wallet
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install dependencies
      run: |
        cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" "./src/webworkers/dist"
        npm install
        npm run build

    - name: Download Artifact Wasm
      run: |
        cd ./dist/build
        mkdir -p wasm
        cd wasm
        
        curl -L  -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://github.com/pandora-cash/go-pandora-pay/release/download/development/artifact-wasm.zip > artifact-wasm.zip 
        unzip artifact-wasm.zip
        
        cd ..
        cd ..
        zip -r wallet-build.zip build

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "release"
        prerelease: false
        files: |
          ./dist/wallet-build.zip
