# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Release Development

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pre-release:
    name: "Release Development"
    runs-on: ubuntu-latest

    steps:

    - name: Checkout wallet
      uses: actions/checkout@v3
    
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Download Artifact Wasm
      run: |
        
        cd ./dist/build/wasm
        
        curl -L  -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://github.com/pandora-cash/go-pandora-pay/releases/download/development/artifact-wasm.zip > artifact-wasm.zip 
        unzip artifact-wasm.zip
        rm artifact-wasm.zip
        
        mv wasm_exec.js ../../../src/webworkers/dist/wasm_exec.js
        
        # rename files
        mv pandora-main-build.wasm PandoraPay-wallet-main.wasm
        mv pandora-main-build.wasm.gz PandoraPay-wallet-main.wasm.gz
        mv pandora-main-build.wasm.br PandoraPay-wallet-main.wasm.br
        
        mv pandora-helper-build.wasm PandoraPay-wallet-helper.wasm
        mv pandora-helper-build.wasm.br PandoraPay-wallet-helper.wasm.br
        mv pandora-helper-build.wasm.gz PandoraPay-wallet-helper.wasm.gz
        
        cd ../../
        (cd build; zip -r ../wallet-build.zip *)

    - name: build npm
      run: |
        npm install
        npm run build        

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "development"
        prerelease: true
        title: "Development Build"
        files: |            
         ./dist/wallet-build.zip
