# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  push:
    tags:
      - "*"

jobs:
  tagged-release:
    name: "Release"

    runs-on: ubuntu-latest
    steps:

    - name: Checkout wallet
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Download Artifact Wasm
      run: |
        mkdir -p ./src/webworkers/dist
        
        mkdir -p ./dist/build/wasm
        cd ./dist/build/wasm
        
        curl -L  -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://github.com/pandora-cash/go-pandora-pay/releases/download/latest/artifact-wasm.zip > artifact-wasm.zip 
        unzip artifact-wasm.zip
        rm artifact-wasm.zip
        
        mv ./wasm_exec.js ../../../src/webworkers/dist/wasm_exec.js
        
        cd ../../
        (cd build; zip -r ../wallet-build.zip *)

    - name: build npm
      run: |
        npm install
        npm run build        

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: |
          ./dist/wallet-build.zip
