# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Release Development

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build release development:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout wallet
      uses: actions/checkout@v3
    
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x        

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install dependencies
      run: |
        cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" "./src/webworkers/dist"
        npm install

    - name: Download Artifact Wasm
      run: |
        cd ./dist/build
        mkdir -p wasm
        cd wasm
        
        curl https://github.com/pandora-cash/go-pandora-pay/releases/download/development/artifact-wasm.zip                      
        unzip artifact-wasm.zip
        
        cd ..
        zip -r wallet-build.zip build

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "development"
          prerelease: true
          title: "Development Build"
          files: |            
           ./dist/wallet-build.zip
